
// Header for module 'example'
// automatically generated by HDLRegs version 0.1 on 2013-11-10 21:00

#ifndef EXAMPLE_REGS_H
#define EXAMPLE_REGS_H

//
// Register address offsets
//
#define ADDR_VERSION 0x00000000
#define ADDR_CONTROL 0x00000100

//
// Fields in register 'VERSION'
//
// Field 'high'
#define OFFSET_VERSION_HIGH 0
#define WIDTH_VERSION_HIGH 8
#define MASK_VERSION_HIGH 0x000000FF

// Field 'low'
#define OFFSET_VERSION_LOW 8
#define WIDTH_VERSION_LOW 8
#define MASK_VERSION_LOW 0x0000FF00


//
// Fields in register 'CONTROL'
//
// Field 'reset'
#define OFFSET_CONTROL_RESET 31
#define WIDTH_CONTROL_RESET 1
#define MASK_CONTROL_RESET 0x80000000

// Field 'done'
#define OFFSET_CONTROL_DONE 1
#define WIDTH_CONTROL_DONE 1
#define MASK_CONTROL_DONE 0x00000002

// Field 'start'
#define OFFSET_CONTROL_START 0
#define WIDTH_CONTROL_START 1
#define MASK_CONTROL_START 0x00000001



#endif // EXAMPLE_REGS_H
